name: Fetch Additional Info

on:
  workflow_call:
    outputs:
      additional_info:
        description: "Additional text extracted from PR comment"
        value: ${{ jobs.extract.outputs.additional_info }}
    secrets:
      GH_TOKEN:
        required: true

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      additional_info: ${{ steps.extract.outputs.additional_info }}
    steps:
      - name: Extract Additional Information from Comment
        id: extract
        run: |
          echo "Extracting additional info from comment..."

          COMMENT_BODY="${{ github.event.comment.body }}"

          # Remove the trigger phrase "help test-engineering" (case-insensitive)
          ADDITIONAL_INFO=$(echo "$COMMENT_BODY" | sed -E 's/^[Hh]elp[[:space:]]+[Tt]est-[Ee]ngineering[[:space:]]*//')

          # If there's remaining text, format it inside a Jira panel
          if [ -n "$ADDITIONAL_INFO" ]; then
            echo "Additional information detected:"
            echo "$ADDITIONAL_INFO"

            FORMATTED_INFO="{panel:bgColor=#eae6ff|title=Additional information}"$'\n'"$ADDITIONAL_INFO"$'\n'"{panel}"
          else
            echo "No additional information provided."
            FORMATTED_INFO=""
          fi

          echo "additional_info<<EOF" >> $GITHUB_OUTPUT
          echo "$FORMATTED_INFO" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
