name: Fetch Failures

on:
  workflow_call:
    inputs:
      pr_head_sha:
        required: true
        type: string
      repo_name:
        required: true
        type: string
    outputs:
      markdown_fragment:
        description: "Markdown fragment listing external check failures"
        value: ${{ jobs.detect.outputs.markdown_fragment }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      markdown_fragment: ${{ steps.build-markdown.outputs.markdown_fragment }}
    steps:
      - name: Fetch Statuses (Argos + Currents)
        id: fetch-statuses
        run: |
          echo "Fetching commit statuses for: ${{ inputs.pr_head_sha }} in repo: ${{ inputs.repo_name }}..."

          STATUS_URL="https://api.github.com/repos/${{ inputs.repo_name }}/commits/${{ inputs.pr_head_sha }}/statuses"
          STATUS_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ vars.GHA_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "$STATUS_URL")

          echo "Raw STATUS_RESPONSE:"
          echo "$STATUS_RESPONSE"

          FAILURES=$(echo "$STATUS_RESPONSE" | jq -r '
            [.[] | select(
              (.state == "failure") and
              (.context | test("argos"; "i") or test("currents"; "i"))
            )]
            | map("| \(.context) | \(.description) | \(.state) | [View Details](\(.target_url // "#")) |")
            | .[]
          ')

          echo "FAILURES<<EOF" >> $GITHUB_ENV
          echo "$FAILURES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build Markdown Output
        id: build-markdown
        run: |
          if [ -n "$FAILURES" ]; then
            echo "Detected failures:"
            echo "$FAILURES"

            MARKDOWN="|| Context || Description || Status || Details ||
            $FAILURES"

            echo "markdown_fragment<<EOF" >> $GITHUB_OUTPUT
            echo "$MARKDOWN" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "✅ No failing statuses detected."
            echo "markdown_fragment=" >> $GITHUB_OUTPUT
          fi
