name: Notify TE on Slack

on:
  workflow_call:
    inputs: 
      jira_ticket_url:
        required: true
        type: string
      jira_ticket_id:
        required: true
        type: string
      mock_mode:
        required: false
        default: "true"
        type: string
      high_priority:
        required: false
        type: string
    # secrets:
    #   SLACK_TOKEN:
    #     required: true
jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:          
      - name: Set Slack channel
        id: channel
        run: |
          if [[ "${{ inputs.mock_mode }}" == "true" ]]; then
            echo "channel=slackbot-testing" >> $GITHUB_OUTPUT
          else
            echo "channel=the-testing-room" >> $GITHUB_OUTPUT
          fi

      - name: Set Slack metadata
        id: slack-meta
        run: |
          REPO_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)
          echo "repo_name=$REPO_NAME"  >> $GITHUB_OUTPUT

          # set slack data based on priority
          if [[ "${{ inputs.high_priority }}" == "true" ]]; then
            echo "color=#e01e5a" >> $GITHUB_OUTPUT
            echo "title=:alert: TE help needed *today*!!" >> $GITHUB_OUTPUT
            echo "notifying_to=@te-goalie and @test-engineers" >> $GITHUB_OUTPUT
            echo "urgency=🔥 This request has been marked *high priority*." >> $GITHUB_OUTPUT
          else
            echo "color=#eed202" >> $GITHUB_OUTPUT
            echo "title=:yellow-alert: TE help was requested!" >> $GITHUB_OUTPUT
            echo "notifying_to=@te-goalie" >> $GITHUB_OUTPUT
            echo "urgency=" >> $GITHUB_OUTPUT
          fi  

          # do not send notification when mock testing
          if [ "${{ inputs.mock_mode }}" == "false" ]; then
            echo "link_names=true" >> $GITHUB_OUTPUT
          else
            echo "color=#3cb371" >> $GITHUB_OUTPUT
            echo "title=:green-alert: This is a mock request!" >> $GITHUB_OUTPUT
            echo "link_names=false" >> $GITHUB_OUTPUT
          fi

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ steps.channel.outputs.channel }}
          SLACK_COLOR: ${{ steps.slack-meta.outputs.color }}
          SLACK_TITLE: ${{ steps.slack-meta.outputs.title }}
          SLACK_MESSAGE: |  
            :empty:
            *Code base*: `${{ steps.slack-meta.outputs.repo_name }}`
            *Pull Request*: <${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.issue.number }}|${{ github.event.issue.title || 'pr title' }} #${{ github.event.issue.number || 'XX' }}> 

            *Notifying to*: ${{ steps.slack-meta.outputs.notifying_to }}
            *Jira ticket*: <${{ inputs.jira_ticket_url }}|${{ inputs.jira_ticket_id }}>

            ${{ steps.slack-meta.outputs.urgency }}
          SLACK_USERNAME: TE Help Bot
          SLACK_ICON_EMOJI: ':robot_face:'
          SLACK_LINK_NAMES: ${{ steps.slack-meta.outputs.link_names }}
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          MSG_MINIMAL: true
