name: Update Comment Before

on:
  workflow_call:
    inputs:
      comment_id:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Add 👀 reaction and feedback message
        uses: actions/github-script@v7
        with:
          script: |
            const commentId = "${{ inputs.comment_id }}";
            const message = `>[!WARNING]
            >We're actively notifying **TE** and creating a JIRA ticket for your request and will update here once completed.`;

            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId,
              content: "eyes"
            });

            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId,
              body: message
            });
